[package]
name = "rtthost"
version = "0.2.0"
edition = "2018"
license = "MIT"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]

[dependencies]
pretty_env_logger = "0.4.0"
probe-rs = { version = "0.10.0" }
probe-rs-rtt = { version = "0.4.0", path = "../probe-rs-rtt" }
structopt = "0.3.11"
